
name: develop sync

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]
jobs:
  if: github.event.pull_request.merged == true
  timeout-minutes: 2
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git Config
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Branch sync script
        run: sh ./.github/merger.sh #add webhook as argument


